id = "js_override"
name = "JS_OVERRIDE"
description = "JavaScript, TypeScript, TSX highlight override."
version = "0.1.0"
schema_version = 1
authors = ["Thomas Gorny <thomas.gorny@pm.me>"]
repository = "https://github.com/zed-industries/zed"


